### ISSUE TITLE
Deploya webbshoppen på GitHub Pages

### ISSUE THREAD

**Issue by codewithina** [mattias012/ReactMovieStore#17]
### Definition of Done
- [x] Följ stegen för att publicera webbappen på GitHub Pages.
- [x] Konfigurera `package.json` med nödvändig information (homepage och deploy-scripts).
- [x] Verifiera att alla routes och sidor fungerar korrekt online.
- [x] Testa att alla funktioner (sök, filtrering, kundvagn, utcheckning) fungerar som förväntat på den publicerade sidan.

**Comment by mattias012** [comment]
Satt upp GH pages från main branch
