### ISSUE TITLE
Skapa startsida med sökfunktion

### ISSUE THREAD

**Issue by codewithina** [mattias012/ReactMovieStore#6]
### Definition of Done
- [x] Skapa en startsida-komponent som visar ett sökfält överst på sidan.
- [x] Använd Redux för att hantera sökningen, hämta och uppdatera filmer från API:t baserat på användarens sökfråga.
- [ ] Visa en lista med filmer som matchar sökningen under sökfältet.
- [x] Hantera tomma sökningar och visa meddelandet "Inga filmer matchar din sökning" om inget resultat hittas.
- [x] Säkerställ att sökresultaten uppdateras dynamiskt utan att sidan laddas om.

**Comment by mattias012** [comment]
Skapat en startsida med sökbar enligt figma-skiss.

**Comment by mattias012** [comment]
Hanterar inte sökresultat i listan under input-fältet.
